### ISSUE TITLE
bqskit-server crashing in detached mode after client disconnects

### ISSUE THREAD

**Issue by alonkukl** [BQSKit/bqskit#293]
I get the following crash:

 ERROR    | base: Traceback (most recent call last):
  File "..../bqskit/runtime/base.py", line 465, in run
    self.handle_message(msg, direction, conn, payload)
  File "...//bqskit/runtime/detached.py", line 139, in handle_message
    self.handle_disconnect(conn)
  File ".../bqskit-1/bqskit/runtime/detached.py", line 265, in handle_disconnect
    tasks_to_pop.append((task_id, tid))
UnboundLocalError: local variable 'task_id' referenced before assignment

Whenever a client disconnects from the server:

```
from bqskit import Circuit
from bqskit.compiler import Compiler
from bqskit.passes import UnfoldPass

passes = [UnfoldPass()]
circuit = Circuit(3)

with Compiler('localhost') as comp:
    out_circ  = comp.compile(circuit, passes)

```

**Comment by alonkukl** [comment]
Solved by #294
